macro(qt)
    set(CMAKE_INCLUDE_CURRENT_DIR ON)
    set(CMAKE_AUTOMOC ON)
    set(CMAKE_AUTOUIC ON)

    find_package(Qt5Widgets)
    find_package(Qt5Network)
    include_directories(${Qt5Widgets_INCLUDE_DIRS} ${Qt5Network_INCLUDE_DIRS})
    qt5_wrap_ui(Window/MainWindow.ui)
endmacro()
